[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[semantic_release]
version_variable = [
  'src/baseproject/__init__.py:__version__',
  'setup.py:__version__'
]
